import { hero } from './hero'
import { feature } from './feature'
import { page } from './page'
import { blog } from './blog'
import { problem } from './problem'
import { service } from './service'
import { homePage } from './homePage'
import { aboutPage } from './aboutPage'
import { doctorsPage } from './doctorsPage'
import { contactPage } from './contactPage'
import { appointmentPage } from './appointmentPage'
import { servicesPage } from './servicesPage'
import { problemsPage } from './problemsPage'
import { footer } from './footer'
import { navbar } from './navbar'

export const schemaTypes = [hero, feature, page, blog, problem, service, homePage, aboutPage, doctorsPage, contactPage, appointmentPage, servicesPage, problemsPage, footer, navbar]
